[build]
  builder = "DOCKERFILE"
  buildCommand = "yarn build"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"
  SERVICE_NAME = "curia-embedding-worker"
  EMBEDDING_RATE_LIMIT = "100"
  EMBEDDING_BATCH_SIZE = "10"
  EMBEDDING_MAX_TEXT_LENGTH = "30000"
  EMBEDDING_RETRY_ATTEMPTS = "3"
  EMBEDDING_RETRY_DELAY_MS = "1000"

  LOG_LEVEL = "info"
  OPENAI_EMBEDDING_MODEL = "text-embedding-3-small" 